language: python
python:
  - "3.8"
  - "3.9"
  - "3.13"
  - "pypy"
  - "pypy3"
install:
  - pip install .
  - pip install -r test/requirements.txt
  - export PATH="$HOME/.local/bin:$PATH"
script:
  - nosetests
